# Default locale used for messages from the 'lang' folder.
# Format: en-US, ru-RU, uk-UA
locale: en-US

# Enables hotbar messages during shooting, reloading.
enable-hotbar-messages: true

# Entity bounding boxes will be uniformly expanded
# (or shrunk) by this value before doing collision checks.
# 0 → precise hitbox
# 0.1 → easier to hit
# -0.05 → harder to hit
ray-size: 0.1

# Time window (in ms) after firing a single shot with an automatic weapon
# during which automatic fire can resume if the player starts sneaking again.
#
# Example:
#   fire-resume-threshold: 1000
#   - Player fires a single shot at T=0 ms
#   - Player sneaks again at T=500 ms → automatic fire resumes
#   - Player sneaks again at T=1200 ms → too late, must click a firing key again
fire-resume-threshold: 1000

# Damage region thresholds based on hit height.
# Each value represents the **minimum normalized Y** required to count as a hit on that body part.
# The values must be in **descending order** (from HEAD to FEET).
#
# Example:
#   If normalizedY > 0.78 → HEAD
#   If normalizedY > 0.40 → BODY
#   If normalizedY > 0.08 → LEGS
#   Else → FEET
damage-thresholds:
  head: 0.78
  body: 0.40
  legs: 0.08

# Each sound is composed of the following properties:
# sound - The sound identifier to play.
#     This can be a built-in Minecraft sound (e.g., 'entity.arrow.hit_player'),
#     or a custom sound defined by a resource pack (e.g., 'custom.ui.click').
#
# category - Controls which volume slider in the client's settings affects the sound.
#     Available categories:
#       - MASTER
#       - MUSIC
#       - RECORDS
#       - WEATHER
#       - BLOCKS
#       - HOSTILE
#       - NEUTRAL
#       - PLAYERS
#       - AMBIENT
#       - VOICE
#
# volume - Controls both loudness and how far the sound can be heard.
#     - Minimum: 0.0 — silent
#     - Default: 1.0 — normal volume and 16-block range
#     - Technically unlimited, but:
#         · If volume ≤ 1.0 → audible within 16 blocks
#         · If volume > 1.0 → audible within (16 × volume) blocks
#         · Example: 2.0 = 32 blocks, 10.0 = 160 blocks
#
# pitch - Affects how high or low the sound is perceived.
#     - Minimum: 0.5 — one octave lower
#     - Default: 1.0 — standard pitch
#     - Maximum: 2.0 — one octave higher
#
# seed - Determines which variation plays for sounds with multiple internal variants.
#     To use a random seed, use -1.
#
# mode - Controls how the sound is played back.
#     - WORLD → Plays the sound at the location in the world so all nearby players can hear it
#     - PLAYER → Plays the sound directly to a single player only
#
# Defaults (if not specified):
#     category: MASTER
#     volume: 1.0
#     pitch: 1.0
#     seed: 0
#     mode: WORLD
sounds:
  entity_hit_head:
    sound: entity.experience_orb.pickup
    category: MASTER
    volume: 0.5
    pitch: 1.0
    seed: 0
    mode: PLAYER
  entity_hit_body:
    sound: block.beehive.drip
    category: MASTER
    volume: 5.0
    pitch: 1.0
    seed: 0
    mode: WORLD
  block_hit:
    sound: block.metal.hit
    category: MASTER
    volume: 2.0
    pitch: 1.0
    seed: 0
    mode: WORLD

# Defines particles to spawn for various events.
# Each entry supports the following fields:
# - particle: A valid Minecraft particle ID (see: https://minecraft.wiki/w/Particles_(Java_Edition))
# - count: Number of particles to spawn (0 disables, default is 1, high values may cause lag)
#
# Some particles require additional data:
#
# 1). Particle: DUST
# ▪ color: Color in format '#RRGGBB'
# ▪ size: Size of the particle [0.01-4.0], default is 1.0
#
# 2). Particle: ITEM
# ▪ item: Non-empty material (see: https://minecraft.wiki/w/Materials for names)
#
# 3). Particle: BLOCK, FALLING_DUST, DUST_PILLAR, BLOCK_MARKER
# ▪ item: Non-empty block material (see: https://minecraft.wiki/w/Block for names)
#
# 4). Particle: DUST_COLOR_TRANSITION
# ▪ from-color: Color in format '#RRGGBB'
# ▪ to-color: Color in format '#RRGGBB'
# ▪ size: Size of the particle [0.01-4.0], default is 1.0
#
# 5). Particle: VIBRATION - UNSUPPORTED
#
# 6). Particle: SCULK_CHARGE
# ▪ roll: Some float value, default is 1.0
#
# 7). Particle: SHRIEK
# ▪ delay: Number of ticks before the particle is spawned, default is 0
#
# 8). Particle: ENTITY_EFFECT
# ▪ color: Color in format '#RRGGBB'
#
particles:
  entity_hit:
    particle: DAMAGE_INDICATOR
    count: 1
  block_hit:
    particle: CRIT
    count: 2

# Armor stand visual features.
# Each feature supports:
#   enabled: true/false — turn on/off the feature (default: true)
#   customModelData: integer — custom model data (default: 0 (vanilla item))
# Some features also have:
#   removeAfter: ticks — how long the feature lasts (20 ticks = 1 second)
armorstand-features:
  # Spawns a bullet hole at the block hit location
  bullet_hole:
    enabled: true
    customModelData: 0
    removeAfter: 200

# List of materials to ignore during ray trace collision checks.
# These materials will be skipped, allowing the ray trace to pass through them.
ignored-materials:
  # 4. FENCE
  - OAK_FENCE
  - SPRUCE_FENCE
  - BIRCH_FENCE
  - JUNGLE_FENCE
  - ACACIA_FENCE
  - CHERRY_FENCE
  - DARK_OAK_FENCE
  - MANGROVE_FENCE
  - BAMBOO_FENCE
  - CRIMSON_FENCE
  - WARPED_FENCE
  - NETHER_BRICK_FENCE
  - IRON_BARS
  # 5. FENCE_GATE
  - OAK_FENCE_GATE
  - SPRUCE_FENCE_GATE
  - BIRCH_FENCE_GATE
  - JUNGLE_FENCE_GATE
  - ACACIA_FENCE_GATE
  - CHERRY_FENCE_GATE
  - DARK_OAK_FENCE_GATE
  - MANGROVE_FENCE_GATE
  - BAMBOO_FENCE_GATE
  - CRIMSON_FENCE_GATE
  - WARPED_FENCE_GATE
  # 6. DOOR
  - OAK_DOOR
  - SPRUCE_DOOR
  - BIRCH_DOOR
  - JUNGLE_DOOR
  - ACACIA_DOOR
  - CHERRY_DOOR
  - DARK_OAK_DOOR
  - MANGROVE_DOOR
  - BAMBOO_DOOR
  - CRIMSON_DOOR
  - WARPED_DOOR
  # 7. TRAPDOOR
  - OAK_TRAPDOOR
  - SPRUCE_TRAPDOOR
  - BIRCH_TRAPDOOR
  - JUNGLE_TRAPDOOR
  - ACACIA_TRAPDOOR
  - CHERRY_TRAPDOOR
  - DARK_OAK_TRAPDOOR
  - MANGROVE_TRAPDOOR
  - BAMBOO_TRAPDOOR
  - CRIMSON_TRAPDOOR
  - WARPED_TRAPDOOR
  # 10. CARPET
  - WHITE_CARPET
  - ORANGE_CARPET
  - MAGENTA_CARPET
  - LIGHT_BLUE_CARPET
  - YELLOW_CARPET
  - LIME_CARPET
  - PINK_CARPET
  - GRAY_CARPET
  - LIGHT_GRAY_CARPET
  - CYAN_CARPET
  - PURPLE_CARPET
  - BLUE_CARPET
  - BROWN_CARPET
  - GREEN_CARPET
  - RED_CARPET
  - BLACK_CARPET
  - MOSS_CARPET
  # 11. CANDLE
  - WHITE_CANDLE
  - ORANGE_CANDLE
  - MAGENTA_CANDLE
  - LIGHT_BLUE_CANDLE
  - YELLOW_CANDLE
  - LIME_CANDLE
  - PINK_CANDLE
  - GRAY_CANDLE
  - LIGHT_GRAY_CANDLE
  - CYAN_CANDLE
  - PURPLE_CANDLE
  - BLUE_CANDLE
  - BROWN_CANDLE
  - GREEN_CANDLE
  - RED_CANDLE
  - BLACK_CANDLE
  - CANDLE
  # 12. BED
  - WHITE_BED
  - ORANGE_BED
  - MAGENTA_BED
  - LIGHT_BLUE_BED
  - YELLOW_BED
  - LIME_BED
  - PINK_BED
  - GRAY_BED
  - LIGHT_GRAY_BED
  - CYAN_BED
  - PURPLE_BED
  - BLUE_BED
  - BROWN_BED
  - GREEN_BED
  - RED_BED
  - BLACK_BED
  # 13. GLASS
  - WHITE_STAINED_GLASS
  - ORANGE_STAINED_GLASS
  - MAGENTA_STAINED_GLASS
  - LIGHT_BLUE_STAINED_GLASS
  - YELLOW_STAINED_GLASS
  - LIME_STAINED_GLASS
  - PINK_STAINED_GLASS
  - GRAY_STAINED_GLASS
  - LIGHT_GRAY_STAINED_GLASS
  - CYAN_STAINED_GLASS
  - PURPLE_STAINED_GLASS
  - BLUE_STAINED_GLASS
  - BROWN_STAINED_GLASS
  - GREEN_STAINED_GLASS
  - RED_STAINED_GLASS
  - BLACK_STAINED_GLASS
  - GLASS
  - TINTED_GLASS
  # 14. GLASS_PANE
  - WHITE_STAINED_GLASS_PANE
  - ORANGE_STAINED_GLASS_PANE
  - MAGENTA_STAINED_GLASS_PANE
  - LIGHT_BLUE_STAINED_GLASS_PANE
  - YELLOW_STAINED_GLASS_PANE
  - LIME_STAINED_GLASS_PANE
  - PINK_STAINED_GLASS_PANE
  - GRAY_STAINED_GLASS_PANE
  - LIGHT_GRAY_STAINED_GLASS_PANE
  - CYAN_STAINED_GLASS_PANE
  - PURPLE_STAINED_GLASS_PANE
  - BLUE_STAINED_GLASS_PANE
  - BROWN_STAINED_GLASS_PANE
  - GREEN_STAINED_GLASS_PANE
  - RED_STAINED_GLASS_PANE
  - BLACK_STAINED_GLASS_PANE
  - GLASS_PANE
  # 17. LEAVES*
  - OAK_LEAVES
  - SPRUCE_LEAVES
  - BIRCH_LEAVES
  - JUNGLE_LEAVES
  - ACACIA_LEAVES
  - CHERRY_LEAVES
  - DARK_OAK_LEAVES
  - MANGROVE_LEAVES
  - AZALEA_LEAVES
  - FLOWERING_AZALEA_LEAVES
  - MANGROVE_ROOTS
  - NETHER_WART_BLOCK
  - WARPED_WART_BLOCK
  - BROWN_MUSHROOM_BLOCK
  - RED_MUSHROOM_BLOCK
  - MUSHROOM_STEM
  - MOSS_BLOCK
  # 18. SAPLING*
  - AZALEA
  - FLOWERING_AZALEA
  # 20. FLOWER*
  - CACTUS
  # 22. GRASS*
  - BIG_DRIPLEAF
  - CHORUS_PLANT
  - CHORUS_FLOWER
  # 23. SEEDS*
  - BAMBOO
  # 24. WATER_STUFF*
  - TURTLE_EGG
  - SNIFFER_EGG
  - LILY_PAD
  - SEA_PICKLE
  - DRIED_KELP_BLOCK
  - SPONGE
  - WET_SPONGE
  # 25. CORAL
  - TUBE_CORAL_BLOCK
  - BRAIN_CORAL_BLOCK
  - BUBBLE_CORAL_BLOCK
  - FIRE_CORAL_BLOCK
  - HORN_CORAL_BLOCK
  # 26. DEAD_CORAL
  - DEAD_TUBE_CORAL_BLOCK
  - DEAD_BRAIN_CORAL_BLOCK
  - DEAD_BUBBLE_CORAL_BLOCK
  - DEAD_FIRE_CORAL_BLOCK
  - DEAD_HORN_CORAL_BLOCK
  # 27. LIGHT*
  - END_ROD
  - LANTERN
  - SOUL_LANTERN
  - SEA_LANTERN
  - REDSTONE_LAMP
  - GLOWSTONE
  - SHROOMLIGHT
  # 28. HEAD*
  - SKELETON_SKULL
  - WITHER_SKELETON_SKULL
  - PLAYER_HEAD
  - ZOMBIE_HEAD
  - CREEPER_HEAD
  - PIGLIN_HEAD
  - DRAGON_HEAD
  # 29. REDSTONE*
  - REPEATER
  - COMPARATOR
  - DAYLIGHT_DETECTOR
  # 30. CAKE
  - CAKE
  # 31. BLOCK*
  - MELON
  - PUMPKIN
  - CARVED_PUMPKIN
  - JACK_O_LANTERN
  - HAY_BLOCK
  - HONEYCOMB_BLOCK
  - SLIME_BLOCK
  - HONEY_BLOCK
  - SNOW
  - SNOW_BLOCK
  # 32. STUFF*
  - FLOWER_POT
  - DECORATED_POT
  - LADDER
  - BREWING_STAND
  - CONDUIT
  - COMPOSTER
  - NOTE_BLOCK
  - JUKEBOX
  - DRAGON_EGG
  - SMALL_AMETHYST_BUD
  - MEDIUM_AMETHYST_BUD
  - LARGE_AMETHYST_BUD
  - AMETHYST_CLUSTER
  - POINTED_DRIPSTONE
  # 33. EXTRA*
  - LIGHT
  - BARRIER
  - COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - STRUCTURE_BLOCK
  - JIGSAW
  - SPAWNER
  - TRIAL_SPAWNER
  - VAULT
  - HEAVY_CORE
  # 34. EXPERIMENTAL
  - ICE
  - PACKED_ICE
  - BLUE_ICE
